version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "16686:16686"
    networks:
    - custom

  stubby4j:
    image: zupacr.azurecr.io/zupme-stubby4j:6.0.1-latest
    ports:
    - "8888:8888"
    environment:
      STUBBY_PORT: 8888
    volumes:
    - ./stubby.yml:/usr/local/stubby.yml
    networks:
    - custom

  payments:
    image: payments-tracing-sample
    ports:
    - "8080:8080"
    networks:
    - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.56.0.0/16
